spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:3306/${DB_NAME}?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    hikari:
      max-lifetime: 500000
      connection-timeout: 30000
      idle-timeout: 600000
      max-pool-size: 20
      minimum-idle: 5
      pool-name: HikariCP
      auto-commit: true
      connection-test-query: SELECT 1
  redis:
    host: 127.0.0.1 
    port: 6379
    database: 0
    password: 
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  lifecycle:
    timeout-per-shutdown-phase: 30s

server:
  port: 6365
  tomcat:
    uri-encoding: UTF-8
    max-thread: 800
    max-connections: 2000
  shutdown: graceful

mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

jwt-secret: ${JWT_SECRET}
log-dir: ${LOG_DIR}
server-addr: ${SERVER_ADDR}
